### ISSUE TITLE
⚡ [Feature]: Improve GitHub Issue Template Guidelines Placement

### ISSUE THREAD

**Issue by PPeitsch** [PPeitsch/pkynetics#41]
### Problem Description
The current GitHub issue templates display the "Guidelines" section at the top of the issue, appearing before the actual content sections. This disrupts the natural issue creation workflow and creates a less intuitive user experience.

### Proposed Solution
Modify issue templates to relocate the guidelines section:
- Move guidelines markdown and checkboxes below the first content section
- Create a more elegant, less intrusive guidelines mechanism
- Ensure guidelines are visible but do not interrupt the issue creation flow

### Alternative Solutions Considered
1. Keep current placement
2. Remove guidelines entirely
3. Create a more compact guidelines notification
4. Use a modal or tooltip for guidelines

### Additional Context
- Applies to all issue templates (Bug, Feature, Documentation)
- Minimal implementation effort
- Aims to reduce friction in issue reporting
- Maintains guideline compliance while improving user experience

### Implementation Details
Potential approaches:
- Reorder template YAML configuration
- Adjust markdown placement
- Modify checkbox section location

```yaml
# Potential template restructuring example
name: Feature Request
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Description
    validations:
      required: true

  # Guidelines now appear after first meaningful input
  - type: checkboxes
    id: guidelines
    attributes:
      label: Contribution Guidelines
      options:
        - label: I've read the contributing guidelines
        - label: I've searched for similar issues
```

### Guidelines

- [X] I agree to follow this project's Contributing Guidelines
- [X] I have searched for similar feature requests
- [X] I understand that this is a request and implementation is not guaranteed
